spring:
  application:
    name: ums-service
    version: 1.0
  eureka:
    client:
      serviceUrl:
        defaultZone: http://service-registry:8761/eureka
      fetch-registry: true
      register-with-eureka: true
server:
  port: 8087

resilience4j.circuitbreaker:
  configs:
    default:
      register-health-indicator: true
      sliding-window-size: 10
      sliding-window-type: count-based
      minimum-number-of-calls: 5
      permitted-number-of-calls-in-half-open-state: 3
      automatic-transition-from-open-to-half-open-enabled: true
      wait-duration-in-open-state: 20s
      failure-rate-threshold: 50
      event-consumer-buffer-size: 10
  instances:
    bssService:
      base-config: default
  circuit-breaker-aspect-order: 2
